/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.io.sofastack.cloud.common.utils;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import io.sofastack.cloud.common.model.TransferRequest;
import io.sofastack.cloud.common.utils.OrderUtils;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.PrivateAccess;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class OrderUtils_SSTest extends OrderUtils_SSTest_scaffolding {
// allCoveredLines:[14, 17, 21, 25, 26, 30, 31, 32, 34, 35]

  @Test(timeout = 4000)
  public void test_currentTimeString_0()  throws Throwable  {
      //caseID:73bed7ee49911176f84d5507d857ef1c
      //CoveredLines: [14, 25, 26]
      //Assert: assertEquals("20140214082121320", method_result);
      
      OrderUtils orderUtils0 = new OrderUtils();
      
      //Call method: currentTimeString
      Object object0 = PrivateAccess.callMethod((Class<OrderUtils>) OrderUtils.class, orderUtils0, "currentTimeString");
      
      //Test Result Assert
      assertEquals("20140214082121320", object0);
  }

  @Test(timeout = 4000)
  public void test_getSerialNo_1()  throws Throwable  {
      //caseID:25f0edf4c867433087fcda6a601f898d
      //CoveredLines: [17, 25, 26, 30, 31, 32]
      //Input_0_TransferRequest: null
      //Assert: assertEquals("20140214082121320000", method_result);
      
      
      //Call method: getSerialNo
      String string0 = OrderUtils.getSerialNo((TransferRequest) null);
      
      //Test Result Assert
      assertEquals("20140214082121320000", string0);
  }

  @Test(timeout = 4000)
  public void test_getSerialNo_2()  throws Throwable  {
      //caseID:b8381f2ec555f2f6ace1f927c9f33233
      //CoveredLines: [17, 25, 26, 30, 34, 35]
      //Input_0_TransferRequest: {getUserId=1000}
      //Assert: assertEquals("20140214082121320001", method_result);
      
      //mock transferRequest0
      TransferRequest transferRequest0 = mock(TransferRequest.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(1000).when(transferRequest0).getUserId();
      
      //Call method: getSerialNo
      String string0 = OrderUtils.getSerialNo(transferRequest0);
      
      //Test Result Assert
      assertEquals("20140214082121320001", string0);
  }

  @Test(timeout = 4000)
  public void test_getSerialNo_3()  throws Throwable  {
      //caseID:ca0f51ab1bd4ad3a7d0ddd2cee2c9e08
      //CoveredLines: [17, 25, 26, 30, 34, 35]
      //Input_0_TransferRequest: {getUserId=1}
      //Assert: assertEquals("20140214082121320002", method_result);
      
      //mock transferRequest0
      TransferRequest transferRequest0 = mock(TransferRequest.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(1).when(transferRequest0).getUserId();
      
      //Call method: getSerialNo
      String string0 = OrderUtils.getSerialNo(transferRequest0);
      
      //Test Result Assert
      assertEquals("20140214082121320002", string0);
  }

  @Test(timeout = 4000)
  public void test_getTradingNo_4()  throws Throwable  {
      //caseID:206d05b6fe6b1893caa7fbb1a664d42f
      //CoveredLines: [21, 25, 26, 30, 34, 35]
      //Input_0_TransferRequest: {}
      //Assert: assertEquals("20140214082121320001", method_result);
      
      //mock transferRequest0
      TransferRequest transferRequest0 = mock(TransferRequest.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: getTradingNo
      String string0 = OrderUtils.getTradingNo(transferRequest0);
      
      //Test Result Assert
      assertEquals("20140214082121320001", string0);
  }
}
